server:
  port: 9995
management: #actuator
  server:
    port: 9996
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

spring:
  application:
    name: DatabaseConnector
  boot:
    admin:
      client:
        instance:
          service-url: http://192.168.10.16:9995
        url: http://192.168.10.16:9995
  datasource:
    hikari:
      pool-name: HikariCP
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 8 # 8 + private
      connection-timeout: 30000
      keepalive-time: 30000
      idle-timeout: 0
      max-lifetime: 0
      connection-test-query: SELECT 1
      register-mbeans: true
    # master 分支必选
    master:
      key: clickhouse
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://192.168.10.15:8123?rewriteBatchedStatements=true
      db: default
      username: default
      password: bjdv2020
      socketTimeout: 6000000
#    cluster:
#      - key: clickhouse1
#        type: com.zaxxer.hikari.HikariDataSource
#        driverClassName: ru.yandex.clickhouse.ClickHouseDriver
#        url: jdbc:clickhouse://192.168.10.15:8123?rewriteBatchedStatements=true
#        db: default
#        username: default
#        password: bjdv2020
#        socketTimeout: 6000000
#  redis:
#    database: 0
#    host: 192.168.10.15
#    password: bjdv2020
#    port: 6379
#    timeout: 300

mqtt:
  clientId: "dbc_prod"
  host: "tcp://192.168.10.15:1883"
  qos: 0
  username: "admin"
  password: "bjdv2020"

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    root: debug